### ISSUE TITLE
Intellisense should know`db` as a predefined name

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-mongodb#14] opened 2017-04-27 17:46 UTC
While testing https://github.com/Microsoft/vscode/issues/25332

Intellisense should know`db` as a predefined name

**Comment by StephenWeatherford** [comment] 2018-04-13 21:58
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  If this issue still reproduces in the newer extension and you would like us to take a look, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues

Thanks!
Stephen

**Closed by StephenWeatherford** 2018-04-13 21:58 UTC
Labels: enhancement
