### ISSUE TITLE
after issuing "Connect" right click command, connection state not in status bar

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-mongodb#17] opened 2017-05-08 04:46 UTC
add a connection to a mongodb server
right click on the database, choose "Connect"

result: no status in the status bar

Now, add a new .mongo scrapbook file

Result: connection is shown in the status bar

expectation: as soon as i say "connect" show the connection in the status bar.

**Comment by StephenWeatherford** [comment] 2018-04-13 21:53
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  If this issue still reproduces in the newer extension and you would like us to take a look, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues

Thanks!
Stephen

**Closed by StephenWeatherford** 2018-04-13 21:53 UTC
