### ISSUE TITLE
command 'mongo.addServer' not found

### ISSUE THREAD

**Issue by endlessracingz** [Microsoft/vscode-mongodb#42] opened 2017-09-20 18:32 UTC
With the latest VS Code x64 v1.16.1, hitting the 'Add Server' button on the extensions gives the Error "command 'mongo.addServer' not found.

This was previously working but I recently updated to v1.16.1 and the extension started providing this error shortly after.

**Comment by LittleHouse75** [comment] 2017-10-06 14:37
Same problem here!  Am I doing something wrong?

**Comment by Drako** [comment] 2017-10-13 10:40
Same problem here!

**Comment by cybercussion** [comment] 2017-10-17 16:57
Had you guys added the "mongo.shell.path": "mongo" ?

**Comment by wierdling** [comment] 2017-10-17 17:20
Added mongo.shell.path and I am also (still) getting this error.
Visual studio code version 1.17.1
Node version 7.9.0
x64

**Comment by cybercussion** [comment] 2017-10-17 20:44
I wonder if it is related to https://github.com/Microsoft/vscode/issues/32353

**Comment by tgbst88** [comment] 2017-10-29 01:13
I am getting the same error:

Version 1.17.2
Shell 1.7.7
Node 7.9.0
Architecture x64

**Comment by roxberry** [comment] 2017-11-30 14:27
+1 - same problem

Visual Studio Code 1.18.1
Shell 1.7.9
Node 7.9
x64

**Comment by tkappeler** [comment] 2017-12-01 13:29
+1 - 

Visual Studio Code 1.18.1
Shell 1.7.9
Node 7.9
x64

**Comment by NTTLuke** [comment] 2017-12-04 22:40
I had same issue and I solved in this way : 

1. Create a file and save it as "mongo.addServer"
2. Inside VS Code  "File - Add Folder to workspace " adding the folder where you have saved the previous file.
3. Add a server by clicking the + button in the title
4. Now it works ! 💃 

I don't know if this is a workaround or the standard one,  but it worked for me.
Hope it works for you too.

**Comment by roxberry** [comment] 2017-12-06 14:50
Observation

1. Open VS Code - no folder selected, use Mongo extension commands - "command 'mongo.addServer' not found", "command 'mongo.newScrapbook' not found", "command 'mongo.refreshExplorer' not found".

2. Open VS Code, open a folder (I created an empty folder named "MongoScrapbooks"), no errors running commands.

3. Open an existing folder (e.g. temp) with VS Code using the context menu, no errors running commands.

I assume it is related to the context.storagePath check in extension.ts line 23 - effectively escaping the registration before any commands can be registered, and subsequently not finding any of the commands.

```
export function activate(context: vscode.ExtensionContext) {
	// Create the storage folder
	**if (context.storagePath) {**
		createStorageFolder(context).then(() => {
			languageClient = new MongoDBLanguageClient(context);
			model = new Model(context.storagePath);
```

I can take a look at the code in test later - maybe add a prompt with more info instead of failing if the location is required to register commands or is there a best practice for extensions?

**Comment by StephenWeatherford** [comment] 2018-04-13 21:48
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  If this issue still reproduces in the newer extension and you would like us to take a look, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues

Thanks!
Stephen

**Closed by StephenWeatherford** 2018-04-13 21:48 UTC
