### ISSUE TITLE
after executing 'exit' command, no other commands can be run 

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-mongodb#1] opened 2017-03-27 20:47 UTC
if i execute `exit` by pressing `F8` and then try to run another command such as `show dbs` I get the following Error:

Error: This socket has been ended by the other party

Refreshing the explorer resets everything so that I can run commands again.

**Comment by StephenWeatherford** [comment] 2018-04-13 22:00
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  If this issue still reproduces in the newer extension and you would like us to take a look, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues

Thanks!
Stephen

**Closed by StephenWeatherford** 2018-04-13 22:00 UTC
