### ISSUE TITLE
"double colon in host identifier" - replica set connection

### ISSUE THREAD

**Issue by galkowskit** [Microsoft/vscode-mongodb#26] opened 2017-07-14 08:09 UTC
After connecting to Replica Set (Atlas) URL I can see the MongoDB connection as the name of the first cluster, I can see the databases in there, but when trying to see the contents of the database all I get is an error saying: "double colon in host identifier".

Any workarounds?

**Comment by StephenWeatherford** [comment] 2018-04-13 21:49
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  If this issue still reproduces in the newer extension and you would like us to take a look, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues

Thanks!
Stephen

**Closed by StephenWeatherford** 2018-04-13 21:49 UTC
