### ISSUE TITLE
Provide intellisense in for queries and projections

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-mongodb#15] opened 2017-04-27 21:13 UTC
While testing https://github.com/Microsoft/vscode/issues/25332.

The extension should provide intellisense on properties and potentially property values when creating a query.
For example:
```js
db.user.find({name: 'kiefer'})
```
Intellisense support could be provided for `name` and for `kiefer`.

Similarly, there should be intellisense support when constructing a projection:
```js
db.user.find({}, { name: 1})
```
Intellisense support could be provided for `name`.

**Comment by StephenWeatherford** [comment] 2018-04-13 21:54
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  If this issue still reproduces in the newer extension and you would like us to take a look, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues

Thanks!
Stephen

**Closed by StephenWeatherford** 2018-04-13 21:54 UTC
Labels: enhancement
