### ISSUE TITLE
When I try to open a database after I logged with a password that contains @ I get the following error: "Username containing an unescaped at-sign"

### ISSUE THREAD

**Issue by claudius76** [Microsoft/vscode-mongodb#43] opened 2017-11-17 02:29 UTC
Steps to reproduce:
1. Add a server with a connection string that has @ inside the password: e.g. 
mongodb://admin:p%40ssword@127.0.0.1:27017/test?authSource=admin
I escaped the @ with %40 because the connection string is an URL.
2. The server is added with success, the connection is made and the databases are read and displayed in the tree.
3. If I click on a database in the tree, I get the following error message: 
[Error - 03:43:45] (node:840) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): Error: Username containing an unescaped at-sign

Here I can see two problems:
- The error message is missleading (not the username contains an @ )
- If the connection was successful using an escaped character, I expect that retrieving collections from a database that was read without error should succeed.

My computer has the following applications installed:
- MongoDB & MongoShell 3.2.3 x64
- Visual Studio Code 1.18.1 x64
- MongoDB Extension 0.0.1

For more information please check the attachment.

![error](https://user-images.githubusercontent.com/6069387/32925326-08ea06e4-cb4a-11e7-8d70-cad7db067653.jpg)

**Comment by StephenWeatherford** [comment] 2018-04-13 21:49
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  If this issue still reproduces in the newer extension and you would like us to take a look, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues

Thanks!
Stephen

**Closed by StephenWeatherford** 2018-04-13 21:49 UTC
