### ISSUE TITLE
'Please connect to the database first' after starting VSCode

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-mongodb#6] opened 2017-04-26 12:54 UTC
Testing https://github.com/Microsoft/vscode/issues/25332

- create a db connection
- open the test db and run some commands
- restart VSCode
- the `_test.mongo` editor is open again
- rerun the same commands

Error dialog: 'Please connect to the database first' 

I have to open the test editor again. 
It would better if reconnecting happens automatic.

**Comment by StephenWeatherford** [comment] 2018-04-13 21:59
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  If this issue still reproduces in the newer extension and you would like us to take a look, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues

There have been several enhancements in this area in the newest version.

Thanks!
Stephen

**Closed by StephenWeatherford** 2018-04-13 21:59 UTC
