### ISSUE TITLE
INVALID text edit warning in console

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-mongodb#7] opened 2017-04-26 13:01 UTC
Testing https://github.com/Microsoft/vscode/issues/25332

- create a db connection
- open the test db and paste `var let = db.inventory.find({status: "A", qty: { $lt: 30 }})`
- press enter and type `re`

Error in console: 'INVALID text edit -> must be single line and on the same line'

The example likely doesn't make any sense...

**Comment by StephenWeatherford** [comment] 2018-04-13 21:59
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  If this issue still reproduces in the newer extension and you would like us to take a look, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues

Thanks!
Stephen

**Closed by StephenWeatherford** 2018-04-13 21:59 UTC
