### ISSUE TITLE
automatically open localhost?

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-mongodb#2] opened 2017-03-27 23:36 UTC
Should we automatically try to open `mongodb://localhost` when the extension starts?  many (most?) will probably have mongo installed locally so its one less thing they have to do.

**Comment by StephenWeatherford** [comment] 2018-04-13 21:56
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  

I've wondered about this functionality myself, so I've moved the issue to there: 
If this issue still reproduces in the newer extension and you would like us to take a look, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues/533

Thanks!
Stephen

**Closed by StephenWeatherford** 2018-04-13 21:56 UTC
